### ISSUE TITLE
Failed Nuxt App building with TypeScript in v1.10.0

### ISSUE THREAD

**Issue by APPLE4869** [nuxt-community/vuetify-module#256]
**Module version**
The version of the module you're using.
@nuxtjs/vuetify v1.10.0
@nuxt/typescript-runtime v0.3.7
@nuxt/typescript-build 0.5.6
Nuxt v2.11.0

**Describe the bug**
On the condition, this bug happen in Nuxt App with TypeScript.

After I updated @nuxtjs/vuetify version to v1.10.0 from v1.9.1, I builded Nuxt App with `nuxt-ts build` and failed with following error.

Do I have to change any settings for Vuetify?

```
✖ Nuxt Fatal Error

TSError: ⨯ Unable to compile TypeScript:  
nuxt.config.ts:222:3 - error TS2322: Type '{ icons: { iconfont: "mdi"; }; customVariables:
string[]; treeShake: true; }' is not assignable to type 'Options'. 
Types of property 'icons' are incompatible.      
Property 'values' is missing in type '{ iconfont: "mdi"; }' but required in type '{ iconfont:   
Iconfont; values: Partial<VuetifyIcons>; }'.     

222   vuetify: {  
~~~~~~~

node_modules/vuetify/types/services/presets.d.ts:27:5       
27     values: Partial<Icons['values']>   
~~~~~~ 
'values' is declared here.     
node_modules/@nuxtjs/vuetify/dist/index.d.ts:6:9 
6         vuetify?: Options;   
~~~~~~~
The expected type comes from property 'vuetify' which is declared here on type
'Configuration' 
```

My current settings for Vuetify in nuxt.config.ts is bellow.

```
  vuetify: {
    icons: {
      iconfont: "mdi"
    },
    customVariables: ["~/assets/stylesheets/vuetify-custom-variables.scss"],
    treeShake: true
  },
```

**To Reproduce**

1. Update your @nuxtjs/vuetify version to v1.10.0 in Nuxt App with TypeScript.
2. Command `nuxt-ts build` in Terminal.
3. You see the error.

**Expected behavior**
Build success.

**Comment by kevinmarrec** [comment]
@APPLE4869 Well Vuetify change their types so I'm not sure what's needed,  could you provide repository with the type error ?

**Comment by clixmat** [comment]
Hi, I managed to fix it after reading the vuetify documentation, here.
https://vuetifyjs.com/en/customization/presets#default-preset

I leave an example of how the configuration should be.

Greetings.

![image](https://user-images.githubusercontent.com/41817274/72324724-8d6e9a00-3679-11ea-9cf5-47e69137d117.png)

**Comment by kevinmarrec** [comment]
Also see : https://github.com/nuxt-community/vuetify-module/blob/next/test/fixture/vuetify.options.ts (cast as `VuetifyPreset` keeps autocompletion working but fix the need to have all properties required)

**Comment by APPLE4869** [comment]
I resolved this issue.
The type VuetifyPreset in Vuetify was changed about icons property.

On the assumption that, version of vuetify what my nuxt app update to v2.2.3 from v2.1.13, while update @nuxtjs/vuetify version to v1.10.0 from v1.9.1.

I checked difference between those versions about icons property and found changed.
Those code is bellow.
Type of `values` property in icons property was changed.

Vuetify v2.2.3
https://github.com/vuetifyjs/vuetify/blob/v2.2.3/packages/vuetify/types/services/presets.d.ts#L27

```
icons: {
  iconfont: Icons['iconfont']
  // TODO: Remove partial for v3
  values: Partial<Icons['values']>
}
```

Vuetify v2.1.13
https://github.com/vuetifyjs/vuetify/blob/v2.1.13/packages/vuetify/types/services/icons.d.ts#L14

```
export interface Icons {
  iconfont: 'mdi' | 'mdiSvg' | 'md' | 'fa' | 'fa4' // TODO: camelCase
  values?: Partial<VuetifyIcons>
}
```

So now I set empty object to values property in my nuxt.config.ts for now, my nuxt building succeeded and ran normally.
Anyways thanks for replying.

```
  vuetify: {
    icons: {
      iconfont: "mdi",
      values: {}
    },
    customVariables: ["~/assets/stylesheets/vuetify-custom-variables.scss"],
    treeShake: true
  },
```
